/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoalCreateCustomRouteImport } from './routes/goal.create-custom'
import { Route as GoalCreateRouteImport } from './routes/goal.create'
import { Route as GoalIdRouteImport } from './routes/goal.$id'
import { Route as GoalCreateFromTemplateTemplateIdRouteImport } from './routes/goal.create-from-template.$templateId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalCreateCustomRoute = GoalCreateCustomRouteImport.update({
  id: '/goal/create-custom',
  path: '/goal/create-custom',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalCreateRoute = GoalCreateRouteImport.update({
  id: '/goal/create',
  path: '/goal/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalIdRoute = GoalIdRouteImport.update({
  id: '/goal/$id',
  path: '/goal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalCreateFromTemplateTemplateIdRoute =
  GoalCreateFromTemplateTemplateIdRouteImport.update({
    id: '/goal/create-from-template/$templateId',
    path: '/goal/create-from-template/$templateId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/goal/$id': typeof GoalIdRoute
  '/goal/create': typeof GoalCreateRoute
  '/goal/create-custom': typeof GoalCreateCustomRoute
  '/goal/create-from-template/$templateId': typeof GoalCreateFromTemplateTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/goal/$id': typeof GoalIdRoute
  '/goal/create': typeof GoalCreateRoute
  '/goal/create-custom': typeof GoalCreateCustomRoute
  '/goal/create-from-template/$templateId': typeof GoalCreateFromTemplateTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/goal/$id': typeof GoalIdRoute
  '/goal/create': typeof GoalCreateRoute
  '/goal/create-custom': typeof GoalCreateCustomRoute
  '/goal/create-from-template/$templateId': typeof GoalCreateFromTemplateTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/goal/$id'
    | '/goal/create'
    | '/goal/create-custom'
    | '/goal/create-from-template/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/goal/$id'
    | '/goal/create'
    | '/goal/create-custom'
    | '/goal/create-from-template/$templateId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/goal/$id'
    | '/goal/create'
    | '/goal/create-custom'
    | '/goal/create-from-template/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  GoalIdRoute: typeof GoalIdRoute
  GoalCreateRoute: typeof GoalCreateRoute
  GoalCreateCustomRoute: typeof GoalCreateCustomRoute
  GoalCreateFromTemplateTemplateIdRoute: typeof GoalCreateFromTemplateTemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal/create-custom': {
      id: '/goal/create-custom'
      path: '/goal/create-custom'
      fullPath: '/goal/create-custom'
      preLoaderRoute: typeof GoalCreateCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal/create': {
      id: '/goal/create'
      path: '/goal/create'
      fullPath: '/goal/create'
      preLoaderRoute: typeof GoalCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal/$id': {
      id: '/goal/$id'
      path: '/goal/$id'
      fullPath: '/goal/$id'
      preLoaderRoute: typeof GoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal/create-from-template/$templateId': {
      id: '/goal/create-from-template/$templateId'
      path: '/goal/create-from-template/$templateId'
      fullPath: '/goal/create-from-template/$templateId'
      preLoaderRoute: typeof GoalCreateFromTemplateTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  GoalIdRoute: GoalIdRoute,
  GoalCreateRoute: GoalCreateRoute,
  GoalCreateCustomRoute: GoalCreateCustomRoute,
  GoalCreateFromTemplateTemplateIdRoute: GoalCreateFromTemplateTemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
